---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-package-manager"
      label: "Package Manager"
    - name: "02-update"
      label: "Update"
    - name: "03-history"
      label: "History"
    - name: "04-rpm-queries"
      label: "Rpm Queries"
    - name: "05-validation"
      label: "Validation"

tabs:
  - name: ">_ terminal"
    url: /wetty/ssh/root
