Package managers are programs which install, update, and remove
software. Doing these operations by hand would be tedious and prone to
mistakes. Bundling these functionalities into a single tool gives users
a more streamlined experience.

DNF has even more utility because it performs dependency resolution
whenever it installs, removes, or updates software. The upcoming steps
will give examples of how to use DNF to streamline your package
management.

== Installing a package with `+dnf+`

Install the network analysis application Wireshark using `+dnf+`. This
application is useful for troubleshooting network packets that are
traveling in and out of your system. This functionality in particular is
not important to this lab, this application was picked simply because it
serves as a good test subject for the upcoming examples.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf -y install wireshark
----

NOTE: The `+-y+` option will automatically answer yes to any prompts
during the installation. Using this option is not best practice when
installing software on your own system, but it is useful for
streamlining some operations in this lab.

This installation generates a large output, so here is a high level
summary of what each section means. The first section shows all of the
packages that must be installed as dependencies for Wireshark:

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Dependencies resolved.
==========================================================================================================================
 Package                                    Arch      Version                 Repository                             Size
==========================================================================================================================
Installing:
 wireshark                                  x86_64    1:4.4.2-3.el10_0        rhel-10-for-x86_64-appstream-rpms     4.6 M
Installing dependencies:
 ModemManager-glib                          x86_64    1.22.0-7.el10           rhel-10-for-x86_64-baseos-rpms        326 k
<< OUTPUT ABRIDGED >>
Installing weak dependencies:
 dconf                                      x86_64    0.40.0-16.el10          rhel-10-for-x86_64-appstream-rpms     111 k
 exiv2                                      x86_64    0.28.3-3.el10_0.2       rhel-10-for-x86_64-appstream-rpms     2.1 M
----

The next section of the output shows an action and status for each
dependent package. In this case, DNF made sure that 136 other packages
were installed or up to date.

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Running transaction
  Preparing        :                                                                                                  1/1 
  Installing       : cairo-1.18.2-2.el10.x86_64                                                                     1/138 
  Installing       : libjpeg-turbo-3.0.2-4.el10.x86_64                                                              2/138
<< OUTPUT ABRIDGED >>
Installed products updated.
----

The final section of the output is a list of all of the packages that
were installed in support of Wireshark’s installation.

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Installed:
  ModemManager-glib-1.22.0-7.el10.x86_64
  adwaita-cursor-theme-46.0-3.el10.noarch                   
  adwaita-icon-theme-46.0-3.el10.noarch
  alsa-lib-1.2.13-2.el10.x86_64                             
  at-spi2-atk-2.52.0-3.el10.x86_64
  at-spi2-core-2.52.0-3.el10.x86_64
<< OUTPUT ABRIDGED >>

Complete!
----

You can verify this installation with the `+dnf list+` command:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf list wireshark
----

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Installed Packages
wireshark.x86_64    1:4.4.2-3.el10_0     @rhel-10-for-x86_64-appstream-rpms
----

This shows how powerful DNF is, as a single command will take care of
the installation seamlessly. Next you will see how to update and remove
packages with `+dnf+`.
