The `+list+` subcommand is useful for finding out which packages have
available updates on the system.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf list updates
----

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Available Upgrades
cloud-init.noarch                                24.4-3.el10_0.2                         rhel-10-for-x86_64-appstream-rpms
git.x86_64                                       2.47.3-1.el10_0                         rhel-10-for-x86_64-appstream-rpms
git-all.noarch                                   2.47.3-1.el10_0                         rhel-10-for-x86_64-appstream-rpms
git-core.x86_64                                  2.47.3-1.el10_0                         rhel-10-for-x86_64-appstream-rpms
<< OUTPUT ABRIDGED >>
----

Many packages on this system have updates available. Specifying a
package name with `+dnf update+` will constrain this operation to only
look for that package.

NOTE: If you instead want to make sure your entire system is up to
date, running `+dnf update+` without any other arguments apply updates
for all packages on your system (including DNF itself).

At the time of writing this lab, the *git* package required an update.
Let’s update *git*. Use the `+-y+` option to automatically say yes to
any prompts for the purposes of this lab.

Feel free to update any additional package listed.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf -y update git
----

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Dependencies resolved.
==========================================================================================================================
 Package                          Architecture   Version                  Repository                                 Size
==========================================================================================================================
Upgrading:
 git                              x86_64         2.47.3-1.el10_0          rhel-10-for-x86_64-appstream-rpms          51 k
 git-all                          noarch         2.47.3-1.el10_0          rhel-10-for-x86_64-appstream-rpms         5.5 k
 git-core                         x86_64         2.47.3-1.el10_0          rhel-10-for-x86_64-appstream-rpms         4.9 M
<< OUTPUT ABRIDGED >>
Transaction Summary
===============================================================
Upgrade  15 Packages
<< OUTPUT ABRIDGED >>
----

NOTE: You sometimes see the subcommand `+upgrade+` being used somewhat
interchangeably with `+update+`. The difference between these two
subcommands is that `+upgrade+` will remove any obsolete packages from
the system. Often the configuration for DNF is such that these
subcommands will both carry out the `+upgrade+` operation.

== Removing a package

Removing a package follows the same theme of simplicity.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf -y remove httpd
----

The extensive output shows you information about which dependent RPMs
were removed as part of this transaction.

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Dependencies resolved.
==========================================================================================================================
 Package                 Architecture      Version                    Repository                                     Size
==========================================================================================================================
Removing:
 httpd                   x86_64            2.4.63-1.el10              @System                                        56 k
Removing dependent packages:
 git-all                 noarch            2.47.3-1.el10_0            @rhel-10-for-x86_64-appstream-rpms              0  
 git-instaweb            noarch            2.47.3-1.el10_0            @rhel-10-for-x86_64-appstream-rpms             45 k

Transaction Summary
==========================================================================================================================
Remove  3 Packages

<< OUTPUT ABRIDGED >>

Removed:
  git-all-2.47.3-1.el10_0.noarch          git-instaweb-2.47.3-1.el10_0.noarch          httpd-2.4.63-1.el10.x86_64         

Complete!
----

Use the `+list+` subcommand to confirm that the package has been
uninstalled:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf list httpd
----

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Available Packages
httpd.x86_64    2.4.63-1.el10    rhel-10-for-x86_64-appstream-rpms
----

The package is now listed as _Available_ rather than _Installed_. The
next step will walk you through `+dnf history+` which provides some more
powerful tools for rolling back package transactions.
