The `+history+` subcommand provides a summary of recent `+dnf+`
transactions.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf history
----

The output contains transaction IDs in the first column, which are how
you reference specific locations in the transaction history when
executing rollbacks.

.Output
[source,text]
----
ID| Command                  | Date and time    | Action(s)| Altered
------------------------------------------------------------------
9 | remove httpd             | 2024-06-12 19:01 | Removed  | 2 EE
8 | update curl -y           | 2024-06-12 18:56 | Upgrade  | 2
7 | install -y wireshark     | 2024-06-12 18:45 | Install  | 197 EE
----

This subcommand is also useful for rolling back transactions if you
erroneously install or update a package, as it cleans up all of the
dependencies associated with the package. Rollback the state of your
system to before you uninstalled *httpd*:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf -y history rollback 8
----

NOTE: The number 8 in the above command signifies the point in time to rollback dnf transactions. 
The system will be in the same state as transaction ID 8, or before you removed *httpd*.

You can use other relative offsets, such as `+last-3+`, or you can use
absolute transaction IDs. For example, `+dnf history rollback 2+` would
rollback to the transaction where *rsync* was installed.

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
Installed:
  httpd-2.4.57-5.el9.x86_64
  httpd-core-2.4.57-5.el9.x86_64

Complete!
----

This command reinstalled the RPMs that are part of *httpd* (including
all dependencies), restoring the system state to how it was before the
previous transaction.

There are many more subcommands that you can use to customize how DNF
behaves. Check out this
https://access.redhat.com/sites/default/files/attachments/rh_yum_cheatsheet_1214_jcs_print-1.pdf[YUM
Command Cheat Sheet for RHEL^] for more info.

NOTE: DNF and YUM are
syntactically identical. You can refer to the YUM cheat sheet for
subcommands that will all work with DNF.
