DNF is the standard package manager, but this does not mean that RPM is
obsolete. Detailed queries can be carried out using RPM using the query
option (`+-q+`). This step will walk you through three examples of how
to use this option.

== Listing files installed by a package

You can combine the `+-q+` option with the list option (`+-l+`) to
display all of the files that are installed by a specific package. This
information is hidden by default to keep the package installation
process simple, but it is often useful to know where specific files are
located.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
rpm -ql wireshark
----

.Output
[source,text]
----
/usr/bin/wireshark
/usr/lib/.build-id
/usr/lib/.build-id/a0
/usr/lib/.build-id/a0/df187e7f23966cfe814708f3e4e3a180c45545
/usr/share/appdata/wireshark.appdata.xml
<< OUTPUT ABRIDGED >>
----

Now you can see that the Wireshark application is located at
`+usr/bin/wireshark+`.

== Listing installation scripts

Some packages run scripts to finish up their installation process. The
`+--scripts+` option can be used in combination with `+rpm -q+` to
return the contents of these postinstall scripts for a specific package.
Wireshark does not actually have any postinstall scripts, so instead try
this command with the *httpd* package.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
rpm -q --scripts httpd
----

The output shows a script that creates a preset for the *httpd* service
behind the scenes when the package is installed.

.Output
[source,text]
----
postinstall scriptlet (using /bin/sh):
 
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then 
    # Initial installation
<< OUTPUT ABRIDGED >>
----

== Showing changelog

Specifying `+--changelog+` with `+rpm -q+` will display what has
recently been changed in a package.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
rpm -q --changelog wireshark
----

.Output
[source,text]
----
* Wed Jul 17 2024 Michal Ruprich <mruprich@redhat.com> - 1:3.4.10-7
- Resolves: RHEL-14596 - Wireshark hangs if dumpcap returned unexpected messages in sync pipe.

* Mon Jun 19 2023 Michal Ruprich <mruprich@redhat.com> - 1:3.4.10-6
- Resolves: #2211413 - XRA dissector infinite loop
<< OUTPUT ABRIDGED >>
----

The next step will walk you through another use for `+rpm+`, file
validation.

