If a program is suddenly misbehaving, it could be related to some key
files not being installed properly. `+rpm+` has a validation option
(`+-V+`) which will compare the local files with the expected files for
the package. Remove a file from the Wireshark package to test out this
validation functionality:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
rm -f /usr/bin/wireshark
----

This command has no expected output.

Use the `+-V+` option with `+rpm+` to check the file status of
Wireshark.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
rpm -V wireshark
----

.Output
[source,text]
----
missing    /usr/bin/wireshark
----

Now that you have seen there is a missing file, reinstall the Wireshark
package to return it to its proper state:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
dnf -y reinstall wireshark
----

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>
==========================================================================================================================
 Package              Architecture      Version                        Repository                                    Size
==========================================================================================================================
Reinstalling:
 wireshark            x86_64            1:4.4.2-3.el10_0               rhel-10-for-x86_64-appstream-rpms            4.6 M
<< OUTPUT ABRIDGED >>
----

Check that *wireshark* has been restored:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
ls -alZ /usr/bin/wireshark
----

.Output
[source,text]
----
-rwxr-xr-x. 1 root root system_u:object_r:wireshark_exec_t:s0 9780392 Jun  5 00:00 /usr/bin/wireshark
----

The command `+rpm -V+` is useful for more than just finding missing
files. This command can inform the user if any files have changed since
installation. To test this out, run the validation command on the PAM
package.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
rpm -V pam
----

.Output
[source,text]
----
S.5....T.  c /etc/security/limits.conf
----

This query returns files with unexpected criteria. The columns of this output shows
this file has an unexpected size, digest, and timestamp. The `c` before the filename 
indicates this file is a configuration file, so it makes sense that it may
be modified after installation to suit the purpose of this particular system.

The columns will either contain a letter for the difference or a dot:

.rpm Verify attributes
* *S* -  file **S**ize differs
* *M* -  **M**ode differs (includes permissions and file type)
* *5* -  digest (formerly MD**5** sum) differs
* *D* -  **D**evice major/minor number mismatch
* *L* -  read**L**ink path mismatch
* *U* -  **U**ser ownership differs
* *G* -  **G**roup ownership differs
* *T* -  m**T**ime differs
* *P* -  ca**P**abilities differ

